# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gtaxllte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gtaxllte/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:system/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/gtaxllte/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/gtaxllte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/gtaxllte/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/gtaxllte/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    vendor/samsung/gtaxllte/proprietary/etc/bluetooth/av_performance.conf:system/etc/bluetooth/av_performance.conf \
    vendor/samsung/gtaxllte/proprietary/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    vendor/samsung/gtaxllte/proprietary/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/samsung/gtaxllte/proprietary/etc/bluetooth/iop_bt.db:system/etc/bluetooth/iop_bt.db \
    vendor/samsung/gtaxllte/proprietary/etc/bluetooth/iop_device_list.conf:system/etc/bluetooth/iop_device_list.conf \
    vendor/samsung/gtaxllte/proprietary/etc/ca.pem:system/etc/ca.pem \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/bdwlan30.bin:system/etc/firmware/bdwlan30.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/bdwlan32.bin:system/etc/firmware/bdwlan32.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/Data.msc:system/etc/firmware/Data.msc \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/nvm_tlv_3.2.bin:system/etc/firmware/nvm_tlv_3.2.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/nvm_tlv_tf_1.1.bin:system/etc/firmware/nvm_tlv_tf_1.1.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/otp30.bin:system/etc/firmware/otp30.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/qwlan30_ibss.bin:system/etc/firmware/qwlan30_ibss.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/qwlan30.bin:system/etc/firmware/qwlan30.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:system/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/rampatch_tlv_tf_1.1.tlv:system/etc/firmware/rampatch_tlv_tf_1.1.tlv \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/utf30.bin:system/etc/firmware/utf30.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/utfbd30.bin:system/etc/firmware/utfbd30.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/utfbd32.bin:system/etc/firmware/utfbd32.bin \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/wlan/grippower.info:system/etc/firmware/wlan/grippower.info \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/wlan/qcom_cfg.ini:system/etc/firmware/wlan/qcom_cfg.ini \
    vendor/samsung/gtaxllte/proprietary/etc/firmware/wlan/WCNSS_cfg.dat:system/etc/firmware/wlan/WCNSS_cfg.dat \
    vendor/samsung/gtaxllte/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/gtaxllte/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/gtaxllte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/gtaxllte/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/gtaxllte/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/gtaxllte/proprietary/lib/hw/audio.primary.universal7870.so:system/lib/hw/audio.primary.universal7870.so \
    vendor/samsung/gtaxllte/proprietary/lib/hw/camera.universal7870.so:system/lib/hw/camera.universal7870.so \
    vendor/samsung/gtaxllte/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/gtaxllte/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/gtaxllte/proprietary/lib/hw/sensors.universal7870.so:system/lib/hw/sensors.universal7870.so \
    vendor/samsung/gtaxllte/proprietary/lib/hw/vulkan.exynos5.so:system/lib/hw/vulkan.exynos5.so \
    vendor/samsung/gtaxllte/proprietary/lib/libOpenCL.so.1.1:system/lib/libOpenCL.so.1.1 \
    vendor/samsung/gtaxllte/proprietary/lib/lib_DNSe_NRSS_ver226.so:system/lib/lib_DNSe_NRSS_ver226.so \
    vendor/samsung/gtaxllte/proprietary/lib/lib_SamsungRec_V05001.so:system/lib/lib_SamsungRec_V05001.so \
    vendor/samsung/gtaxllte/proprietary/lib/lib_SoundAlive_SRC384_ver300.so:system/lib/lib_SoundAlive_SRC384_ver300.so \
    vendor/samsung/gtaxllte/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/gtaxllte/proprietary/lib/lib_SoundBooster_ver700.so:system/lib/lib_SoundBooster_ver700.so \
    vendor/samsung/gtaxllte/proprietary/lib/libaudioroute.so:system/lib/libaudioroute.so \
    vendor/samsung/gtaxllte/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/samsung/gtaxllte/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    vendor/samsung/gtaxllte/proprietary/lib/libcodecdump.so:system/lib/libcodecdump.so \
    vendor/samsung/gtaxllte/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/gtaxllte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/gtaxllte/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/gtaxllte/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/gtaxllte/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/gtaxllte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/gtaxllte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/gtaxllte/proprietary/lib/libpreprocessing_nxp.so:system/lib/libpreprocessing_nxp.so \
    vendor/samsung/gtaxllte/proprietary/lib/libSamsungPostProcess.so:system/lib/libSamsungPostProcess.so \
    vendor/samsung/gtaxllte/proprietary/lib/libSamsungPostProcessConvertor.so:system/lib/libSamsungPostProcessConvertor.so \
    vendor/samsung/gtaxllte/proprietary/lib/libSamsungPreProcess.so:system/lib/libSamsungPreProcess.so \
    vendor/samsung/gtaxllte/proprietary/lib/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
    vendor/samsung/gtaxllte/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/gtaxllte/proprietary/lib/libsamsungSoundbooster_plus.so:system/lib/libsamsungSoundbooster_plus.so \
    vendor/samsung/gtaxllte/proprietary/lib/libsecaudioinfo.so:system/lib/libsecaudioinfo.so \
    vendor/samsung/gtaxllte/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/gtaxllte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/gtaxllte/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/gtaxllte/proprietary/lib/libstainkiller.so:system/lib/libstainkiller.so \
    vendor/samsung/gtaxllte/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/gtaxllte/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/samsung/gtaxllte/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/gtaxllte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/gtaxllte/proprietary/lib/modules/qca_cld/qca_cld_wlan.ko:system/lib/modules/qca_cld/qca_cld_wlan.ko \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/gtaxllte/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/gtaxllte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/gtaxllte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/gtaxllte/proprietary/vendor/firmware/setfile_4h5yc.bin:system/vendor/firmware/setfile_4h5yc.bin \
    vendor/samsung/gtaxllte/proprietary/vendor/firmware/setfile_sr259.bin:system/vendor/firmware/setfile_sr259.bin \
    vendor/samsung/gtaxllte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/gtaxllte/proprietary/vendor/lib/libLifevibes_lvverx.so:system/vendor/lib/libLifevibes_lvverx.so \
    vendor/samsung/gtaxllte/proprietary/vendor/lib/libLifevibes_lvvetx.so:system/vendor/lib/libLifevibes_lvvetx.so \
    vendor/samsung/gtaxllte/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/gtaxllte/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/gtaxllte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/gtaxllte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_COPY_FILES += \
    vendor/samsung/gtaxllte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/gtaxllte/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/gtaxllte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/gtaxllte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/gtaxllte/proprietary/lib/librilutils.so:system/lib/librilutils.so \

PRODUCT_COPY_FILES += \
    vendor/samsung/gtaxllte/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh

#    vendor/samsung/gtaxllte/proprietary/lib/libril.so:system/lib/libril.so \
#    vendor/samsung/gtaxllte/proprietary/bin/rild:system/bin/rild \
